services:
  reservation:
    container_name: reservation-service
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: pnpm start:dev reservation
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm start:dev auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    container_name: reservation-mongo
    ports:
      - '27017:27017'
